### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ISE9218** [UsboKirishima/krokodil#1]

**Comment by UsboKirishima** [comment]
You can use krokodil directly downloading the official .exe file [CLICK HERE](https://github.com/UsboKirishima/krokodil/releases/download/v1.0.0/krokodil.exe) or building it from source running the command `make win` and open the .exe file built in the `build/krokodil.exe` directory of the project (this requires to manual install each dependency [maybe soon I'll make an installer for windows]).

*Sincerely -usbo*
