### ISSUE TITLE
The commit history is unreadable

### ISSUE THREAD

**Issue by wowthisiscrazy123** [UsboKirishima/krokodil#2]
If you want to see the actual commit history, I cloned the repository and removed all the commits that contained "security: security check" (spoiler: they weren't security checks).

You can find the actual commit history [here](https://github.com/giogiga/krokodil).

Do I know why the source was hidden? No, I don't.
Was it done because this is a malware? Probably, but I'm nowhere good enough in C to know for sure.

But really, I can't think of any other reasons why you'd want to (shamefully) hide the entire commit history.

**Comment by UsboKirishima** [comment]
that's not a try to hide the commits history, these commits are generated by a bash script to make checks on the code, but it left a lot of useless commits in the history. If you think this repo contains bad software you can read the source code or put it on a virus scanner.

sincerely, usbe

**Comment by wowthisiscrazy123** [comment]
@UsboKirishima Cool!
What is that bash script? Is it open source?
How was it used to make checks? Why did it leave commits that added a single number to a file? Why didn't you delete the commits afterwards (you can still do it now)?
